version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Install kaitai-struct-compiler
          command: |
            sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 379CE192D401AB61
            echo "deb https://dl.bintray.com/kaitai-io/debian jessie main" | sudo tee /etc/apt/sources.list.d/kaitai.list
            sudo -i apt-get update
            sudo -i apt-get install kaitai-struct-compiler
            ksc --version
      - run:
          name: Install Ruby dependencies
          command: |
            cd _build
            bundle install
      - run:
          name: Build HTML
          command: |
            ./build
