version: 2
jobs:
  build:
    docker:
#      - image: ubuntu:17.10
#      - image: buildpack-deps:artful-scm
      - image: circleci/buildpack-deps:stable-scm
    environment:
      - LANG=en_US.UTF-8
      - LC_CTYPE=en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Download submodules
          command: git submodule update --init --recursive
      - run:
          name: Install apt deps
          command: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends -y dirmngr
            sudo apt-key add <.circleci/bintray.key
            #apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 379CE192D401AB61
            echo "deb http://dl.bintray.com/kaitai-io/debian jessie main" | sudo tee /etc/apt/sources.list.d/kaitai.list
            sudo apt-get update
            sudo apt-get install --no-install-recommends -y \
              git ssh \
              locales \
              kaitai-struct-compiler default-jre-headless \
              ruby ruby-dev make gcc libc6-dev bundler \
              graphviz \
              rsync
            ksc --version
      - run:
          name: Fix locales
          command: |
            echo 'en_US.UTF-8 UTF-8' | sudo tee /etc/locale.gen
            echo 'LANG="en_US.UTF-8"' | sudo tee /etc/default/locale
            sudo dpkg-reconfigure --frontend=noninteractive locales
            locale
      - run:
          name: Install Ruby deps
          command: |
            echo 'gem: --no-document' | sudo tee /etc/gemrc
            cd _build
            bundle install
      - run:
          name: Build targets
          command: |
            locale
            cd _build
            ./build-target .. target
      - store_artifacts:
          # Storing artifacts is slow, so we only store the log; we'll
          # get target files in HTML anyway
          path: _build/target/log.json
      - run:
          name: Build diagrams
          command: |
            cd _build
            ./build-diagrams target html
      - run:
          name: Build HTML
          command: |
            cd _build
            ./build-html .. target html
      - run:
          name: Deploy HTML
          command: |
            .circleci/publish
