version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run:
          name: Install apt deps
          command: |
            apt-get update
            apt-get install --no-install-recommends -y dirmngr
            apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 379CE192D401AB61
            echo "deb http://dl.bintray.com/kaitai-io/debian jessie main" | tee /etc/apt/sources.list.d/kaitai.list
            apt-get update
            apt-get install --no-install-recommends -y default-jre-headless kaitai-struct-compiler ruby ruby-dev
            ksc --version
      - run:
          name: Install Ruby deps
          command: |
            gem install bundler
            cd _build
            bundle install
      - run:
          name: Build HTML
          command: |
            cd _build
            ./build
